# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alternator < Formula
  desc "alternator"
  homepage "https://github.com/kota65535/alternator"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kota65535/alternator/releases/download/v0.2.1/alternator_darwin_arm64.tar.gz"
      sha256 "cffd28d1815b16d2789dee22a1233f0a1363476841660302bd335be64f427dc5"

      def install
        bin.install "alternator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kota65535/alternator/releases/download/v0.2.1/alternator_darwin_amd64.tar.gz"
      sha256 "e4039f5abf7267cc4bd99041d25bbdc634735386d25621d3a838c820efaede30"

      def install
        bin.install "alternator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kota65535/alternator/releases/download/v0.2.1/alternator_linux_arm64.tar.gz"
      sha256 "0aecc1a736095c4f2c5316e72b9bea092fd6286b92eeec65fafce8a0837d1ea9"

      def install
        bin.install "alternator"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kota65535/alternator/releases/download/v0.2.1/alternator_linux_armv6.tar.gz"
      sha256 "4deed5136da6f0e64a86d949962a3ce960b66b7b8a14e284e009e52b2d5b8c51"

      def install
        bin.install "alternator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kota65535/alternator/releases/download/v0.2.1/alternator_linux_amd64.tar.gz"
      sha256 "10dd04a327a423ebd35b58cb67c9f807c4828cf827986c507c4adc99af6ba681"

      def install
        bin.install "alternator"
      end
    end
  end
end
