# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alternator < Formula
  desc "alternator"
  homepage "https://github.com/kota65535/alternator"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kota65535/alternator/releases/download/v0.1.9/alternator_darwin_x86_64.tar.gz"
      sha256 "92da893e983dd32d59778cf6178173046d5753cc24b64009a19c1965850c7cfc"

      def install
        bin.install "alternator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kota65535/alternator/releases/download/v0.1.9/alternator_darwin_arm64.tar.gz"
      sha256 "9da85548f786e036d70e8e9c1dfb4b4766a0e70fbcb9a989b90834fbb727f54f"

      def install
        bin.install "alternator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kota65535/alternator/releases/download/v0.1.9/alternator_linux_armv6.tar.gz"
      sha256 "b073df34c0c8e10be3aa597cd4feae752fa9819821edb787bd2cfd78de5bd58d"

      def install
        bin.install "alternator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kota65535/alternator/releases/download/v0.1.9/alternator_linux_arm64.tar.gz"
      sha256 "7685ce2f2a20ea05f4ba31a972e0b3f5dea40d5ede496424a0ff604593480d12"

      def install
        bin.install "alternator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kota65535/alternator/releases/download/v0.1.9/alternator_linux_x86_64.tar.gz"
      sha256 "218c041a500aa8b327ce3415261ce77349636286585532645128333f3abc3dcf"

      def install
        bin.install "alternator"
      end
    end
  end
end
